#!/bin/env python

import argparse
import xml.sax
import zipfile

recognized_text_properties = {
  'fo:background-color',
  'fo:color',
  'fo:country', # NOT DISPLAYED
  'fo:font-size',
  'fo:font-weight',
  'fo:hyphenate',
  'fo:hyphenation-push-char-count',
  'fo:hyphenation-remain-char-count',
  'fo:language', # NOT DISPLAYED
  'fo:text-shadow',
  'style:font-name',
  'style:font-relief',
  'style:text-underline-color',
  'style:text-underline-style',
  'style:text-underline-width',
  'style:use-window-font-color',
}

#------------------------------------------------------------------------------
class context_parser(xml.sax.ContentHandler):
  def __init__(self, root_parser):
    xml.sax.ContentHandler.__init__(self)
    self.root_parser = root_parser

  def beginContext(self, name, attrs):
    pass

  def endContext(self):
    pass

#------------------------------------------------------------------------------
class parse_style_tab_stops(context_parser):
  #----------------------------------------------------------------------------
  def __init__(self, root_parser):
    context_parser.__init__(self, root_parser)
    self.stops = []

  #----------------------------------------------------------------------------
  def startElement(self, name, attrs):
    if name == 'style:tab-stop':
      self.stops.append(attrs)

  #----------------------------------------------------------------------------
  def endContext(self):
    if not len(self.stops):
      return

    text = ''
    for stop in self.stops:
      if len(text):
        text += ', '

      text += stop['style:position']
      if 'style:type' in stop:
        text += ' ' + stop['style:type']

    print '  tab-stops: %s;' % text

#------------------------------------------------------------------------------
def print_attr(attrs, key, display_name):
  if key in attrs:
    common_value = attrs[key]
    print '  %s: %s;' % (display_name, common_value)

    asian_key = key + '-asian'
    if asian_key in attrs and attrs[asian_key] != common_value:
      print '  %s-asian: %s;' % (display_name, attrs[asian_key])

    complex_key = key + '-complex'
    if complex_key in attrs and attrs[complex_key] != common_value:
      print '  %s-complex: %s;' % (display_name, attrs[complex_key])

#------------------------------------------------------------------------------
class parse_style_style(context_parser):
  #----------------------------------------------------------------------------
  def beginContext(self, name, attrs):
    # Only handle named non-default styles
    if name == 'style:style' and 'style:display-name' in attrs:
      if 'style:class' in attrs:
        print '%s:%s."%s" {' % (attrs['style:family'], attrs['style:class'],
                                attrs['style:display-name'])
      else:
        print '%s."%s" {' % (attrs['style:family'],
                              attrs['style:display-name'])

      self.in_style = True;

    # Handle default styles
    elif name == 'style:default-style':
      print '%s {' % attrs['style:family']
      self.in_style = True;

    # If an unnamed non-default style, cancel the context
    else:
      self.root_parser.popContext()

  #----------------------------------------------------------------------------
  def endContext(self):
    print '}\n'

  #----------------------------------------------------------------------------
  def startElement(self, name, attrs):
    if name == 'style:tab-stops':
      self.root_parser.setContext(parse_style_tab_stops(self.root_parser))

    elif name == 'style:text-properties':
      print_attr(attrs, 'fo:background-color', 'background-color')
      print_attr(attrs, 'fo:color', 'color')
      if 'style:use-window-font-color' in attrs:
        print '  font-color: window;'
      print_attr(attrs, 'style:font-name', 'font-name')
      print_attr(attrs, 'fo:font-size', 'font-size')
      print_attr(attrs, 'fo:font-weight', 'font-weight')

      if 'style:text-underline-style' in attrs:
        underline_style = attrs['style:text-underline-style']
        if 'style:text-underline-width' in attrs:
          underline_style += ' ' + attrs['style:text-underline-width']
        if 'style:text-underline-color' in attrs:
          underline_style += ' ' + attrs['style:text-underline-color']
        print '  text-underline: %s;' % underline_style

      print_attr(attrs, 'fo:text-shadow', 'text-shadow')
      print_attr(attrs, 'style:font-relief', 'text-relief')

      if 'fo:hyphenate' in attrs:
        text = attrs['fo:hyphenate']
        if 'fo:hyphenation-push-char-count' in attrs:
          text += ' ' + attrs['fo:hyphenation-push-char-count']
        elif 'fo:hyphenation-remain-char-count' in attrs:
          text += ' auto'
        if 'fo:hyphenation-remain-char-count' in attrs:
          text += ' ' + attrs['fo:hyphenation-remain-char-count']
        print '  hyphenate: %s;' % text

      for attr in attrs.keys():
        if attr.endswith('-asian') or attr.endswith('-complex'):
          continue;
        if not attr in recognized_text_properties:
          print '  /* unhandled text-properties attribute \'%s\' */' % attr

    else:
      print '  /* unhandled tag \'%s\' */' % name

#------------------------------------------------------------------------------
class style_parser(xml.sax.ContentHandler):
  #----------------------------------------------------------------------------
  def __init__(self):
    xml.sax.ContentHandler.__init__(self)

    self.context_parsers = []
    self.context_tags = []

    self.current_name = None
    self.current_attrs = {}

  #----------------------------------------------------------------------------
  def setContext(self, context):
    self.context_tags.append(self.current_name)
    self.context_parsers.append(context)
    context.beginContext(self.current_name, self.current_attrs)

  #----------------------------------------------------------------------------
  def popContext(self):
    self.context_parsers.pop()
    self.context_tags.pop()

  #----------------------------------------------------------------------------
  def startElement(self, name, attrs):
    self.current_name = name
    self.current_attrs = attrs

    if len(self.context_parsers):
      self.context_parsers[-1].startElement(name, attrs);

    if name == 'style:style' or name == 'style:default-style':
      self.setContext(parse_style_style(self))

  #----------------------------------------------------------------------------
  def endElement(self, name):
    if len(self.context_tags) and name == self.context_tags[-1]:
      self.context_parsers[-1].endContext()
      self.popContext()

    if len(self.context_parsers):
      self.context_parsers[-1].endElement(name);

#------------------------------------------------------------------------------
def print_raw(archive, filename):
  data = archive.read(filename)
  print data

#------------------------------------------------------------------------------
def parse_xml(archive, filename, parser):
  data = archive.read(filename)
  xml.sax.parseString(data, parser)

#------------------------------------------------------------------------------
def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('document',
                      help='path to document to convert')
  parser.add_argument('--raw', dest='raw', action='store_const',
                      const=True, default=False,
                      help='print raw XML')
  parser.add_argument('--style', dest='style', action='store_const',
                      const=True, default=False,
                      help='include simplified style markup')

  args = parser.parse_args()
  archive = zipfile.ZipFile(args.document)

  # Are we reading the raw XML?
  if args.raw:
    # Print style (if requested) and content, then exit
    args.style and print_raw(archive, 'styles.xml')
    print_raw(archive, 'content.xml')
    return

  if args.style:
    parse_xml(archive, 'styles.xml', style_parser())

  # TODO
  for info in archive.infolist():
    print info.filename

#------------------------------------------------------------------------------
if __name__ == '__main__':
  main()
